import { Header } from "@/client/components/Header/Header";
import { LayoutWrapper, Main } from "@/client/components/Main/Main.styles";
import { Sidebar } from "@/client/components/Sidebar/Sidebar";
import { UserContext } from "@/client/contexts/user/user";
import { ThemeProvider } from "@/client/theme/ThemeProvider";
import { getSubject } from "@/server/dashboard/getSubject";
import { login } from "@/server/user/login";
import { Box } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import GlobalStyles from "@mui/material/GlobalStyles";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globalicons.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ISpot | Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  ...rest
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await login();
  const brand = await getSubject(user.brandsOfInterest[0].id);

  console.log({ user, rest, brand });
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider>
            <UserContext user={{ ...user, selectedSubject: brand }}>
              <GlobalStyles
                styles={{
                  ["*"]: {
                    boxSizing: "border-box",
                    padding: 0,
                    margin: 0,
                  },
                  body: {
                    maxWidth: "100vw",
                    overflowX: "hidden",
                  },
                  html: {
                    maxWidth: "100vw",
                    overflowX: "hidden",
                  },
                }}
              />
              <Box
                display={"flex"}
                flexDirection={"column"}
                height="100vh"
                width="100vw"
              >
                <Header />
                <LayoutWrapper>
                  <Sidebar />
                  <Main>{children}</Main>
                </LayoutWrapper>
              </Box>
            </UserContext>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
